framework:
    assets:
        packages:
            shop:
                json_manifest_path: '%kernel.project_dir%/public/assets/shop/manifest.json'
            admin:
                json_manifest_path: '%kernel.project_dir%/public/assets/admin/manifest.json'
