when@test: &test
    services:
        Sylius\Component\Core\Generator\ImagePathGeneratorInterface:
            class: Sylius\Behat\Service\Generator\UploadedImagePathGenerator

when@test_cached: *test
