# config/packages/sylius_twig_hooks.yaml
sylius_twig_hooks:
    hooks:
        'sylius_shop.base.header.content.logo':
            content:
                template: 'templates/shared/logo.html.twig'
                priority: 0
