imports:
    - { resource: "@SyliusAdyenPlugin/config/config.yaml" }

parameters:
    sylius_refund.supported_gateways:
        - offline
        - adyen

sylius_twig_hooks:
    hooks:
        'sylius_admin.order.show.content.sections.payments.item.actions':
            send_payment_link:
                enabled: false
            adyen_send_payment_link:
                template: '@SyliusAdyenPlugin/admin/order/content/sections/payments/item/actions/send_payment_link.html.twig'
                priority: 100

        'sylius_shop.cart.index.content.form.sections.general#right':
            express_checkout:
                enabled: false
            adyen_express_checkout:
                template: '@SyliusAdyenPlugin/shop/cart/index/content/form/sections/general/express_checkout.html.twig'
                priority: -100
