twig_component:
    anonymous_template_directory: 'components/'
    defaults:
        # Namespace & directory for components
        Sylius\Bundle\UiBundle\Twig\Component\: '@SyliusUiBundle/Twig/Component/'
        App\Twig\Components\: 'components/'
