name: sylius_standard
recipe: symfony
config:
    php: '8.0'
    xdebug: true
    webroot: public
    database: mysql
    config:
        php: .lando/php.ini

services:
    database:
        portforward: true
        creds:
            database: sylius_dev
        host: database
        port: 3306
    appserver:
        build_as_root:
            - apt-get install zlib1g fontconfig libxrender1 libfreetype6 libxext6 libx11-6 libjpeg62-turbo-dev libjpeg-dev -y
            - cp .lando/bin/wkhtmltopdf .lando/bin/wkhtmltoimage /usr/local/bin
        overrides:
            environment:
                LANDO_HOST_IP: "host.docker.internal"
                XDEBUG_CONFIG: "remote_enable=1 remote_host=host.docker.internal"
                PHP_IDE_CONFIG: "serverName=sylius_standard.lndo.site"
                PHP_INI_XDEBUG__REMOTE_PORT: "9003"
            extra_hosts:
                - ${LANDO_HOST_IP_DEV:-host}:host-gateway

tooling:
    behat:
        service: appserver
        cmd: vendor/bin/behat
        description: Runs behat tests
    spec:
        service: appserver
        cmd: vendor/bin/phpspec
        description: Runs PHPSpec
    unit:
        service: appserver
        cmd: vendor/bin/phpunit
        description: Runs PHPUnit
    cc:
        service: appserver
        cmd: rm -fr var/cache
        description: Forcefully Clears cache
