version: "3.4"

services:
    php:
        build:
            context: .
            target: sylius_php_dev
        environment:
            # See https://docs.docker.com/docker-for-mac/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host
            # See https://github.com/docker/for-linux/issues/264
            # The `remote_host` below may optionally be replaced with `remote_connect_back` (eg: linux users)
            XDEBUG_CONFIG: >-
                remote_enable=1
                remote_host=host.docker.internal
                remote_port=9001
                idekey=PHPSTORM
            # This should correspond to the server declared in PHPStorm `Preferences | Languages & Frameworks | PHP | Servers`
            # Then PHPStorm will use the corresponding path mappings
            PHP_IDE_CONFIG: serverName=sylius
