# app/config/emails.yml
sylius_mailer:
    sender:
        name: Marinewool.ru
        address: no-reply@marinewool.ru
    emails:
        contact_request:
            subject: sylius.emails.contact_request.subject
            template: "contactRequest.html.twig"
        order_confirmation:
            subject: sylius.emails.order_confirmation.subject
            template: "orderConfirmation.html.twig"
        shipment_confirmation:
            subject: sylius.emails.shipment_confirmation.subject
            template: "shipmentConfirmation.html.twig"
        user_registration:
            subject: sylius.emails.user_registration.subject
            template: "userRegistration.html.twig"
        password_reset:
            subject: sylius.emails.user.password_reset.subject
            template: "passwordReset.html.twig"
        reset_password_token:
            subject: sylius.emails.user.password_reset.subject
            template: "passwordReset.html.twig"
        reset_password_pin:
            subject: sylius.emails.user.password_reset.subject
            template: "passwordReset.html.twig"
        verification_token:
            subject: sylius.emails.user.verification_token.subject
            template: "verification.html.twig"