version: '3.4'

services:
    sylius:
        env_file:
            - .env.prod

    assets:
        env_file:
            - .env.prod

    webserver:
        # in production, we may want to use a static website hosting service
        env_file:
            - .env.prod
        volumes:
            # use a bind-mounted host directory, as we want to keep the media
            - ./public/media:/srv/sylius/public/media:ro

    mysql:
        env_file:
            - .env.prod
        volumes:
            - mysql-data-prod:/var/lib/mysql:rw

volumes:
    mysql-data-prod:
