version: '3.4'

services:
    sylius:
        deploy:
            resources:
                limits:
                    memory: 512M

    assets:
        deploy:
            resources:
                limits:
                    memory: 256M

    mysql:
        deploy:
            resources:
                limits:
                    memory: 512M

    mailhog:
        deploy:
            resources:
                limits:
                    memory: 512M

volumes:
    mysql-data:
    public-media:
