name: Build Docker Image

on:
    push:
        branches:
            - 'master'
        paths-ignore:
            - "*.md"
    pull_request:
        branches:
            - 'master'
        paths-ignore:
            - "*.md"

jobs:
    build-image:
        name: Build Docker Image and Test Docker Compose
        env:
            MYSQL_PASSWORD: sylius-mysql
            DOCKER_BUILDKIT: 1 # Requires Latest Buildx in docker CLI
            COMPOSE_DOCKER_CLI_BUILD: 1 # Requires Latest Buildx in docker compose CLI
        strategy:
            fail-fast: false
            matrix:
                platform: [linux/amd64,linux/arm64]
                docker_compose: [docker-compose.yml,docker-compose.prod.yml]
                targets: [sylius_nginx,sylius_php]
        
        runs-on: ubuntu-latest
        steps:
            -
                name: Set Up QEMU
                uses: docker/setup-qemu-action@v2
            -
                name: Set Up Docker Buildx
                uses: docker/setup-buildx-action@v2
                
            -
                name: Login to DockerHub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -
                name: Build Image
                uses: docker/build-push-action@v3
                with:
                    push: true
                    platforms: ${{ matrix.platform }}
                    tags: ferror/sylius-demo:${{ matrix.target }}
                    cache-from: type=gha
                    cache-to: type=gha
                    load: true
                    target: ${{ matrix.target }}
