# Admin Notes Suite Configuration
default:
    suites:
        ui_admin_notes:
            contexts:
                - sylius.behat.context.hook.bad_gateway
                - sylius.behat.context.hook.doctrine_orm
                - sylius.behat.context.hook.session

                - sylius.behat.context.transform.admin
                - sylius.behat.context.transform.channel
                - sylius.behat.context.transform.customer
                - sylius.behat.context.transform.order
                - sylius.behat.context.transform.product

                - sylius.behat.context.setup.admin_security
                - sylius.behat.context.setup.admin_user
                - sylius.behat.context.setup.channel
                - sylius.behat.context.setup.customer
                - sylius.behat.context.setup.order
                - sylius.behat.context.setup.product
                - sylius.behat.context.setup.taxonomy

                - sylius.behat.context.ui.admin.managing_orders
                - sylius.behat.context.ui.save
                - App\Tests\Behat\Context\Admin\Order\AdminNotesContext
                - App\Tests\Behat\Context\Order\OrderSetupContext

            paths:
                - "%paths.base%/features/admin/order/admin_notes.feature"
                - "%paths.base%/features/shop/order/admin_notes_not_visible.feature"

            filters:
                tags: "@admin_notes||@admin_notes_not_visible"

